global:
  configMapName: tantran2prod-configmap
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  keyCloakURL: http://keycloak:80/realms/master/protocol/openid-connect/certs