version: "3.8"
services:
  configserver:
    image: tantran2/configserver:latest
    mem_reservation: 700m
    ports:
      - "8071:8071"
    networks:
      - bank-network
  eurekaserver:
    image: tantran2/eurekaserver:latest
#    restart: always
    mem_reservation: 700m
    ports:
      - "8070:8070"
    networks:
      - bank-network
    depends_on:
      configserver:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 15
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
  accounts:
    image: tantran2/microservice_accounts_service:latest
    mem_reservation: 700m
    ports:
      - "8080:8080"
    networks:
      - bank-network
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 15
        window: 5s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  loans:
    image: tantran2/microservice_loans_service:latest
    mem_reservation: 700m
    ports:
      - "8090:8090"
    networks:
      - bank-network
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 15
        window: 5s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  cards:
    image: tantran2/microservice_cards_service:latest
    mem_reservation: 700m
    ports:
      - "9000:9000"
    networks:
      - bank-network
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 15
        window: 5s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  gatewayserver:
    image: tantran2/gatewayserver:latest
    mem_reservation: 500m
    ports:
      - "8072:8072"
    networks:
      - bank-network
    depends_on:
       configserver:
           condition: service_started
       eurekaserver:
           condition: service_started
       cards:
           condition: service_started
       accounts:
           condition: service_started
       loans:
           condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 15
        window: 5s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
networks:
  bank-network: