version: "3.8"
services:
  accounts:
    image: microservice/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - bank-network
  loans:
    image: microservice/loans:latest
    ports:
      - "8090:8090"
    networks:
      - bank-network
  cards:
    image: microservice/cards:latest
    ports:
      - "9000:9000"
    networks:
      - bank-network
networks:
  bank-network: