deploymentName: eurekaserver-deployment
deploymentLabel: eurekaserver

replicaCount: 1

image:
  repository: tantran2/eurekaserver
  tag: latest

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070

config_enabled: true
profile_enabled: true
eureka_enabled: false
keycloak_enabled: false