deploymentName: cards-deployment
deploymentLabel: cards

replicaCount: 1

image:
  repository: tantran2/microservice_cards_service
  tag: latest
containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

config_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false